# common_target_test - Task 13A + 15: Common target logits & sensitivity (10/20/50 states)
Chuyen tu `common_target_test.py` sang `.ipynb` giu nguyen logic, chi sua duong dan checkpoint sang `output Training` (ckpt-60/ckpt-64).
- DQN logits: q_network linear 14 -> reduce_mean
- A2C_mod logits: actor.layer4 linear truoc softmax
- Chay SHAP PartitionExplainer 660-dim, background 100, test 10/20/50 mau

**Cach chay trong notebook:** chinh `CONFIG` o cell 2 roi Run All. Khong dung argparse nhu ban .py.

In [1]:
import os, warnings, time, numpy as np, pandas as pd, tensorflow as tf, shap
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"
warnings.filterwarnings("ignore")

# === CONFIG thay cho argparse (sua truc tiep o day) ===
CONFIG = {
    "n_states": [10, 20, 50],
    "scenarios": ["EASY", "MEDIUM", "HARD"],
    "nsamples": 2000,
    "data_dir": r"C:\GitHub\Q-learning-for-Inventory-Management\data",
    "dqn_ckpt": r"C:\GitHub\Q-learning-for-Inventory-Management\output Training\checkpointDQN",
    "a2c_ckpt": r"C:\GitHub\Q-learning-for-Inventory-Management\output Training\outputA2Cmod\checkpoints_a2cmod",
    "out_dir": r"C:\GitHub\Q-learning-for-Inventory-Management\Feedback 7-9\task11-9",
}
print(f"CONFIG n_states={CONFIG['n_states']} scenarios={CONFIG['scenarios']}")
print(f"DQN ckpt -> {tf.train.latest_checkpoint(CONFIG['dqn_ckpt'])}")
print(f"A2C ckpt -> {tf.train.latest_checkpoint(CONFIG['a2c_ckpt'])}")

NUM_PRODUCTS = 220
NUM_FEATURES_PP = 3
NUM_FEATURES = 660
NUM_ACTIONS = 14
WASTE_RATE = 0.025

CONFIG n_states=[10, 20, 50] scenarios=['EASY', 'MEDIUM', 'HARD']
DQN ckpt -> C:\GitHub\Q-learning-for-Inventory-Management\output Training\checkpointDQN\ckpt-60
A2C ckpt -> C:\GitHub\Q-learning-for-Inventory-Management\output Training\outputA2Cmod\checkpoints_a2cmod\ckpt-64

In [2]:
# Model classes (copy tu topk_shap_analysis.ipynb:171-281)
class Dense(tf.Module):
    def __init__(self, input_dim, output_size, activation=None, stddev=1.0):
        super().__init__()
        self.w=tf.Variable(tf.random.truncated_normal([input_dim, output_size], stddev=stddev), name="w")
        self.b=tf.Variable(tf.zeros([output_size]), name="b")
        self.activation=activation
    def __call__(self,x):
        y=tf.matmul(x,self.w)+self.b
        if self.activation: y=self.activation(y)
        return y

class Actor(tf.Module):
    def __init__(self, num_features, num_actions, hidden_size, activation=tf.nn.relu, dropout_prob=0.1):
        super().__init__()
        self.layer1=Dense(num_features, hidden_size)
        self.layer2=Dense(hidden_size, hidden_size)
        self.layer3=Dense(hidden_size, hidden_size)
        self.layer4=Dense(hidden_size, num_actions)
        self.activation=activation
        self.dropout_prob=dropout_prob
    def __call__(self,state):
        x=self.activation(self.layer1(state))
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.activation(self.layer2(x))
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.activation(self.layer3(x))
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.layer4(x)
        return tf.nn.softmax(x)
    def logits(self,state):
        x=self.activation(self.layer1(state))
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.activation(self.layer2(x))
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.activation(self.layer3(x))
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.layer4(x)
        return x

class Critic(tf.Module):
    def __init__(self, num_features, hidden_size, activation=tf.nn.relu, dropout_prob=0.1):
        super().__init__()
        self.layer1=Dense(num_features, hidden_size)
        self.layer2=Dense(hidden_size, 1)
        self.activation=activation
        self.dropout_prob=dropout_prob
        self.group_norm=tf.keras.layers.GroupNormalization(groups=1)
    def __call__(self,state):
        x=self.layer1(state)
        x=self.group_norm(x)
        x=self.activation(x)
        x=tf.nn.dropout(x,self.dropout_prob)
        x=self.layer2(x)
        return tf.squeeze(x, axis=-1)

class MultiProductQNetwork(tf.keras.Model):
    def __init__(self, num_features, num_products, num_actions, hidden_size, dropout_prob=0.1, use_group_norm=True):
        super().__init__()
        self.num_products=num_products
        self.num_actions=num_actions
        self.features_per_prod=num_features//num_products
        self.dense1=tf.keras.layers.Dense(hidden_size, activation=None)
        self.dense2=tf.keras.layers.Dense(hidden_size, activation=None)
        self.dense3=tf.keras.layers.Dense(hidden_size, activation=None)
        self.out=tf.keras.layers.Dense(num_actions, activation=None)
        self._use_gn=use_group_norm
        if use_group_norm:
            self.gn1=tf.keras.layers.GroupNormalization(groups=1)
            self.gn2=tf.keras.layers.GroupNormalization(groups=1)
            self.gn3=tf.keras.layers.GroupNormalization(groups=1)
        self.drop1=tf.keras.layers.Dropout(dropout_prob)
        self.drop2=tf.keras.layers.Dropout(dropout_prob)
        self.drop3=tf.keras.layers.Dropout(dropout_prob)
    def call(self,state,training=False):
        B=tf.shape(state)[0]
        P,F=self.num_products,self.features_per_prod
        s3d=tf.transpose(tf.reshape(state,[B,F,P]),[0,2,1])
        x=tf.reshape(s3d,[B*P,F])
        x=self.dense1(x)
        if self._use_gn: x=self.gn1(x, training=training)
        x=tf.nn.relu(x); x=self.drop1(x, training=training)
        x=self.dense2(x)
        if self._use_gn: x=self.gn2(x, training=training)
        x=tf.nn.relu(x); x=self.drop2(x, training=training)
        x=self.dense3(x)
        if self._use_gn: x=self.gn3(x, training=training)
        x=tf.nn.relu(x); x=self.drop3(x, training=training)
        return tf.reshape(self.out(x),[B,P,self.num_actions])

In [3]:
# === Load models ===
print("[common_target] Loading agents...")
actor=Actor(3,14,32)
critic=Critic(3,32)
_=actor(tf.zeros([1,3])); _=critic(tf.zeros([1,3]))
a2c_ckpt=tf.train.Checkpoint(critic_optimizer=tf.optimizers.Adam(0.0005), actor_optimizer=tf.optimizers.Adam(0.0001), critic=critic, actor=actor, step=tf.Variable(0))
a2c_latest=tf.train.latest_checkpoint(CONFIG["a2c_ckpt"])
if a2c_latest is None:
    raise FileNotFoundError(f"A2C checkpoint not found in {CONFIG['a2c_ckpt']}")
a2c_ckpt.restore(a2c_latest).expect_partial()
print("A2C restored", a2c_latest)
q_net=MultiProductQNetwork(660,220,14,32)
t_net=MultiProductQNetwork(660,220,14,32)
_=q_net(tf.zeros([1,660],dtype=tf.float32), training=False); _=t_net(tf.zeros([1,660],dtype=tf.float32), training=False)
dqn_ckpt=tf.train.Checkpoint(optimizer=tf.optimizers.Adam(0.001), q_network=q_net, target_network=t_net, step=tf.Variable(0))
dqn_latest=tf.train.latest_checkpoint(CONFIG["dqn_ckpt"])
if dqn_latest is None:
    raise FileNotFoundError(f"DQN checkpoint not found in {CONFIG['dqn_ckpt']}")
dqn_ckpt.restore(dqn_latest).expect_partial()
print("DQN restored", dqn_latest)

def _parse(s,key,n):
    return tf.io.parse_single_example(s,{key:tf.io.FixedLenFeature([n],tf.float32)})[key]
cap_file=os.path.join(CONFIG["data_dir"],"capacity.tfrecords")
stock_file=os.path.join(CONFIG["data_dir"],"stock.tfrecords")
test_file=os.path.join(CONFIG["data_dir"],"test.tfrecords")
capacity=next(iter(tf.data.TFRecordDataset(cap_file).map(lambda s:_parse(s,"capacity",220)))).numpy()
x_init=next(iter(tf.data.TFRecordDataset(stock_file).map(lambda s:_parse(s,"stock",220)))).numpy()
all_sales=[]
for rec in tf.data.TFRecordDataset(test_file).map(lambda s:_parse(s,"sales",220)):
    all_sales.append(rec.numpy())
all_sales=np.array(all_sales,dtype=np.float32)/capacity[None,:]
print(f"Data loaded {all_sales.shape} capacity {capacity.shape}")

np.random.seed(42)
bg=np.zeros((100,660),dtype=np.float32)
bg[:,:220]=np.random.uniform(0,1,size=(100,220))
bg[:,220:440]=np.random.uniform(0,1,size=(100,220))
bg[:,440:]=np.clip(0.025*bg[:,:220]+np.random.normal(0,0.005,size=(100,220)),0,0.1)

def dqn_logits_660(X):
    if not isinstance(X,np.ndarray): X=np.array(X,dtype=np.float32)
    q=q_net(X, training=False)
    return tf.reduce_mean(q, axis=1).numpy()
def a2c_logits_660(X):
    if not isinstance(X,np.ndarray): X=np.array(X,dtype=np.float32)
    B=X.shape[0]
    s3d=tf.transpose(tf.reshape(X,[B,3,220]),[0,2,1])
    s_pp=tf.reshape(s3d,[B*220,3])
    logits=actor.logits(s_pp)
    logits_3d=tf.reshape(logits,[B,220,14])
    return tf.reduce_mean(logits_3d, axis=1).numpy()
def a2c_pi_660(X):
    if not isinstance(X,np.ndarray): X=np.array(X,dtype=np.float32)
    B=X.shape[0]
    s3d=tf.transpose(tf.reshape(X,[B,3,220]),[0,2,1])
    s_pp=tf.reshape(s3d,[B*220,3])
    probs=actor(s_pp)
    probs_3d=tf.reshape(probs,[B,220,14])
    return tf.reduce_mean(probs_3d, axis=1).numpy()
def a2c_critic_660(X):
    if not isinstance(X,np.ndarray): X=np.array(X,dtype=np.float32)
    B=X.shape[0]
    s3d=tf.transpose(tf.reshape(X,[B,3,220]),[0,2,1])
    s_pp=tf.reshape(s3d,[B*220,3])
    v=critic(s_pp)
    v_3d=tf.reshape(v,[B,220])
    return tf.reduce_mean(v_3d, axis=1, keepdims=True).numpy()

def get_feature_info(idx):
    if idx<220: return ("inventory", idx)
    elif idx<440: return ("sales", idx-220)
    else: return ("waste_feat", idx-440)
feature_names=[f"{get_feature_info(i)[0]}_SKU{get_feature_info(i)[1]}" for i in range(660)]
feature_groups=[get_feature_info(i)[0] for i in range(660)]
sku_ids=[get_feature_info(i)[1] for i in range(660)]

SCENARIOS={"EASY":{"scale":0.5,"waste":0.010},"MEDIUM":{"scale":1.0,"waste":0.025},"HARD":{"scale":1.5,"waste":0.050}}
all_rows=[]
for sc in CONFIG["scenarios"]:
    scale=SCENARIOS[sc]["scale"]
    waste=SCENARIOS[sc]["waste"]
    for n in CONFIG["n_states"]:
        sales=all_sales[:n]*scale
        test=np.zeros((n,660),dtype=np.float32)
        test[:,:220]=x_init[None,:]
        test[:,220:440]=sales
        test[:,440:]=x_init[None,:]*waste
        print(f"\n=== {sc} n={n} test {test.shape} ===")
        for name, fn in [("DQN_logits", dqn_logits_660), ("A2C_logits", a2c_logits_660)]:
            print(f"  Running {name}...")
            masker=shap.maskers.Partition(bg, max_samples=100)
            explainer=shap.PartitionExplainer(fn, masker)
            sv=explainer(test)
            arr=sv.values if hasattr(sv,"values") else np.array(sv)
            if arr.ndim==3:
                imp=np.mean(np.abs(arr), axis=(0,2))
            else:
                imp=np.mean(np.abs(arr), axis=0)
            top_idx=np.argsort(imp)[-20:][::-1]
            for rank, idx in enumerate(top_idx,1):
                all_rows.append({"Agent":name.split("_")[0] if "DQN" in name else "A2C_mod","Scenario":sc,"n_states":n,"Target":"logits","Rank":rank,"FeatureName":feature_names[idx],"MacroGroup":feature_groups[idx],"SKU_ID":sku_ids[idx],"MeanAbsSHAP":float(imp[idx])})
            print(f"  {name} Top-5 {[feature_names[i] for i in top_idx[:5]]}")

df=pd.DataFrame(all_rows)
out1=os.path.join(CONFIG["out_dir"],"outputTask11_common_target.csv")
df.to_csv(out1, index=False, encoding="utf-8-sig")
print(f"Saved {out1} shape {df.shape}")
df.head(10)

[common_target] Loading agents...
A2C restored C:\GitHub\Q-learning-for-Inventory-Management\output Training\outputA2Cmod\checkpoints_a2cmod\ckpt-64
DQN restored C:\GitHub\Q-learning-for-Inventory-Management\output Training\checkpointDQN\ckpt-60
Data loaded (504, 220) capacity (220,)

=== EASY n=10 test (10, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 2/10 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 4/10 [00:23<00:22,  3.79s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 5/10 [00:30<00:26,  5.24s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 6/10 [00:37<00:24,  6.00s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 7/10 [00:45<00:19,  6.44s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 8/10 [00:52<00:13,  6.69s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 9/10 [00:59<00:06,  6.87s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 10/10 [01:06<00:00,  7.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 11it [01:14,  8.25s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU164', 'sales_SKU119', 'sales_SKU157']
  Running A2C_logits...

PartitionExplainer explainer: 11it [00:44,  5.56s/it]

  A2C_logits Top-5 ['sales_SKU93', 'sales_SKU119', 'sales_SKU108', 'sales_SKU175', 'sales_SKU71']

=== EASY n=20 test (20, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 2/20 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 4/20 [00:22<00:58,  3.67s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  25%|██▌       | 5/20 [00:29<01:17,  5.20s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 6/20 [00:36<01:24,  6.01s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  35%|███▌      | 7/20 [00:44<01:24,  6.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 8/20 [00:51<01:21,  6.80s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  45%|████▌     | 9/20 [00:59<01:17,  7.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 10/20 [01:06<01:12,  7.22s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  55%|█████▌    | 11/20 [01:14<01:06,  7.36s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 12/20 [01:22<00:59,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  65%|██████▌   | 13/20 [01:29<00:52,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 14/20 [01:37<00:45,  7.52s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  75%|███████▌  | 15/20 [01:44<00:37,  7.53s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 16/20 [01:52<00:30,  7.56s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  85%|████████▌ | 17/20 [01:59<00:22,  7.53s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 18/20 [02:07<00:15,  7.60s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  95%|█████████▌| 19/20 [02:15<00:07,  7.58s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 20/20 [02:22<00:00,  7.59s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 21it [02:30,  7.91s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU164', 'sales_SKU119', 'sales_SKU157']
  Running A2C_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 21it [01:37,  5.15s/it]

  A2C_logits Top-5 ['sales_SKU93', 'sales_SKU90', 'sales_SKU119', 'sales_SKU108', 'sales_SKU157']

=== EASY n=50 test (50, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   4%|▍         | 2/50 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   8%|▊         | 4/50 [00:22<02:57,  3.85s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 5/50 [00:31<04:17,  5.72s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  12%|█▏        | 6/50 [00:38<04:40,  6.38s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  14%|█▍        | 7/50 [00:46<04:50,  6.76s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  16%|█▌        | 8/50 [00:53<04:52,  6.96s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  18%|█▊        | 9/50 [01:01<04:54,  7.17s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 10/50 [01:08<04:48,  7.22s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  22%|██▏       | 11/50 [01:15<04:45,  7.33s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  24%|██▍       | 12/50 [01:23<04:40,  7.38s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  26%|██▌       | 13/50 [01:31<04:36,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  28%|██▊       | 14/50 [01:38<04:28,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 15/50 [01:45<04:20,  7.45s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  32%|███▏      | 16/50 [01:53<04:13,  7.44s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  34%|███▍      | 17/50 [02:00<04:06,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  36%|███▌      | 18/50 [02:08<03:59,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  38%|███▊      | 19/50 [02:15<03:51,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 20/50 [02:23<03:44,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  42%|████▏     | 21/50 [02:30<03:36,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  44%|████▍     | 22/50 [02:38<03:29,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  46%|████▌     | 23/50 [02:45<03:21,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  48%|████▊     | 24/50 [02:53<03:14,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 25/50 [03:00<03:07,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  52%|█████▏    | 26/50 [03:08<02:59,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  54%|█████▍    | 27/50 [03:15<02:51,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  56%|█████▌    | 28/50 [03:23<02:44,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  58%|█████▊    | 29/50 [03:30<02:37,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 30/50 [03:38<02:29,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  62%|██████▏   | 31/50 [03:45<02:22,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  64%|██████▍   | 32/50 [03:53<02:14,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  66%|██████▌   | 33/50 [04:00<02:08,  7.53s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  68%|██████▊   | 34/50 [04:08<01:59,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 35/50 [04:15<01:52,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  72%|███████▏  | 36/50 [04:23<01:44,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  74%|███████▍  | 37/50 [04:30<01:37,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  76%|███████▌  | 38/50 [04:37<01:29,  7.45s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  78%|███████▊  | 39/50 [04:45<01:22,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 40/50 [04:52<01:14,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  82%|████████▏ | 41/50 [05:00<01:08,  7.56s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  84%|████████▍ | 42/50 [05:08<01:00,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  86%|████████▌ | 43/50 [05:15<00:52,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  88%|████████▊ | 44/50 [05:23<00:45,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 45/50 [05:30<00:37,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  92%|█████████▏| 46/50 [05:38<00:29,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  94%|█████████▍| 47/50 [05:45<00:22,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  96%|█████████▌| 48/50 [05:53<00:14,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  98%|█████████▊| 49/50 [06:00<00:07,  7.57s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 50/50 [06:08<00:00,  7.59s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 51it [06:15,  7.67s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU164', 'sales_SKU119', 'sales_SKU157']
  Running A2C_logits...

PartitionExplainer explainer:  18%|█▊        | 9/50 [00:39<03:04,  4.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 10/50 [00:44<03:07,  4.70s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  44%|████▍     | 22/50 [01:42<02:14,  4.80s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  46%|████▌     | 23/50 [01:47<02:12,  4.93s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  48%|████▊     | 24/50 [01:53<02:13,  5.15s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 25/50 [01:58<02:10,  5.24s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  54%|█████▍    | 27/50 [02:08<01:58,  5.15s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  72%|███████▏  | 36/50 [02:53<01:08,  4.92s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 51it [04:06,  5.13s/it]

  A2C_logits Top-5 ['sales_SKU93', 'sales_SKU71', 'sales_SKU90', 'sales_SKU108', 'sales_SKU119']

=== MEDIUM n=10 test (10, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 2/10 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 4/10 [00:22<00:22,  3.72s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 5/10 [00:29<00:26,  5.26s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 6/10 [00:37<00:24,  6.13s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 7/10 [00:44<00:19,  6.59s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 8/10 [00:52<00:13,  6.85s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 9/10 [00:59<00:07,  7.07s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 10/10 [01:07<00:00,  7.20s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 11it [01:14,  8.32s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU119', 'sales_SKU164', 'sales_SKU157']
  Running A2C_logits...

PartitionExplainer explainer:  50%|█████     | 5/10 [00:19<00:12,  2.45s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 11it [00:49,  6.13s/it]

  A2C_logits Top-5 ['sales_SKU119', 'sales_SKU93', 'sales_SKU90', 'sales_SKU108', 'sales_SKU175']

=== MEDIUM n=20 test (20, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 2/20 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 4/20 [00:22<00:59,  3.72s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  25%|██▌       | 5/20 [00:30<01:19,  5.33s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 6/20 [00:37<01:26,  6.18s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  35%|███▌      | 7/20 [00:44<01:25,  6.60s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 8/20 [00:52<01:22,  6.87s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  45%|████▌     | 9/20 [00:59<01:17,  7.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 10/20 [01:07<01:11,  7.16s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  55%|█████▌    | 11/20 [01:14<01:05,  7.28s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 12/20 [01:22<00:58,  7.33s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  65%|██████▌   | 13/20 [01:29<00:51,  7.39s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 14/20 [01:37<00:44,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  75%|███████▌  | 15/20 [01:44<00:37,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 16/20 [01:52<00:29,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  85%|████████▌ | 17/20 [01:59<00:22,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 18/20 [02:07<00:14,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  95%|█████████▌| 19/20 [02:14<00:07,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 20/20 [02:22<00:00,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 21it [02:29,  7.88s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU164', 'sales_SKU119', 'sales_SKU157']
  Running A2C_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  35%|███▌      | 7/20 [00:29<00:56,  4.34s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 20/20 [01:32<00:00,  4.84s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 21it [01:38,  5.16s/it]

  A2C_logits Top-5 ['sales_SKU93', 'sales_SKU71', 'sales_SKU119', 'sales_SKU108', 'sales_SKU90']

=== MEDIUM n=50 test (50, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   4%|▍         | 2/50 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   8%|▊         | 4/50 [00:22<03:01,  3.94s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 5/50 [00:30<04:06,  5.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  12%|█▏        | 6/50 [00:37<04:33,  6.21s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  14%|█▍        | 7/50 [00:45<04:48,  6.71s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  16%|█▌        | 8/50 [00:53<04:56,  7.07s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  18%|█▊        | 9/50 [01:00<04:56,  7.22s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 10/50 [01:08<04:53,  7.34s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  22%|██▏       | 11/50 [01:15<04:48,  7.39s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  24%|██▍       | 12/50 [01:23<04:46,  7.55s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  26%|██▌       | 13/50 [01:31<04:40,  7.58s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  28%|██▊       | 14/50 [01:39<04:31,  7.55s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 15/50 [01:46<04:24,  7.56s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  32%|███▏      | 16/50 [01:54<04:15,  7.53s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  34%|███▍      | 17/50 [02:01<04:07,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  36%|███▌      | 18/50 [02:08<03:59,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  38%|███▊      | 19/50 [02:16<03:51,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 20/50 [02:24<03:45,  7.52s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  42%|████▏     | 21/50 [02:31<03:39,  7.56s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  44%|████▍     | 22/50 [02:39<03:31,  7.54s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  46%|████▌     | 23/50 [02:46<03:22,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  48%|████▊     | 24/50 [02:54<03:15,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 25/50 [03:01<03:07,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  52%|█████▏    | 26/50 [03:09<02:59,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  54%|█████▍    | 27/50 [03:16<02:51,  7.47s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  56%|█████▌    | 28/50 [03:23<02:44,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  58%|█████▊    | 29/50 [03:31<02:38,  7.54s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 30/50 [03:40<02:38,  7.92s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  62%|██████▏   | 31/50 [03:48<02:32,  8.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  64%|██████▍   | 32/50 [03:57<02:26,  8.11s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  66%|██████▌   | 33/50 [04:05<02:19,  8.22s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  68%|██████▊   | 34/50 [04:14<02:14,  8.42s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 35/50 [04:23<02:10,  8.67s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  72%|███████▏  | 36/50 [04:33<02:04,  8.89s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  74%|███████▍  | 37/50 [04:41<01:53,  8.76s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  76%|███████▌  | 38/50 [04:49<01:43,  8.66s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  78%|███████▊  | 39/50 [04:58<01:35,  8.73s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 40/50 [05:07<01:27,  8.77s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  82%|████████▏ | 41/50 [05:19<01:27,  9.68s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  84%|████████▍ | 42/50 [05:30<01:21, 10.20s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  86%|████████▌ | 43/50 [05:39<01:08,  9.78s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  88%|████████▊ | 44/50 [05:48<00:56,  9.43s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 45/50 [05:57<00:46,  9.28s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  92%|█████████▏| 46/50 [06:06<00:36,  9.18s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  94%|█████████▍| 47/50 [06:14<00:27,  9.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  96%|█████████▌| 48/50 [06:23<00:18,  9.05s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  98%|█████████▊| 49/50 [06:33<00:09,  9.15s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 50/50 [06:44<00:00,  9.82s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 51it [06:56,  8.50s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU164', 'sales_SKU90', 'sales_SKU119', 'sales_SKU157']
  Running A2C_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   4%|▍         | 2/50 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   8%|▊         | 4/50 [00:22<02:44,  3.57s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 5/50 [00:28<03:28,  4.64s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  12%|█▏        | 6/50 [00:34<03:46,  5.15s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  14%|█▍        | 7/50 [00:40<03:43,  5.20s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  16%|█▌        | 8/50 [00:46<03:54,  5.58s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  18%|█▊        | 9/50 [00:52<03:55,  5.75s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 10/50 [00:58<03:51,  5.79s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  22%|██▏       | 11/50 [01:05<03:59,  6.13s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  24%|██▍       | 12/50 [01:11<03:52,  6.11s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  26%|██▌       | 13/50 [01:17<03:48,  6.16s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  28%|██▊       | 14/50 [01:23<03:40,  6.12s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 15/50 [01:30<03:37,  6.21s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  32%|███▏      | 16/50 [01:36<03:30,  6.20s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  34%|███▍      | 17/50 [01:42<03:23,  6.16s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  36%|███▌      | 18/50 [01:48<03:14,  6.07s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  38%|███▊      | 19/50 [01:54<03:07,  6.05s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 20/50 [02:00<03:01,  6.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  42%|████▏     | 21/50 [02:06<02:53,  5.98s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  44%|████▍     | 22/50 [02:12<02:48,  6.00s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  46%|████▌     | 23/50 [02:18<02:42,  6.01s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  48%|████▊     | 24/50 [02:24<02:37,  6.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 25/50 [02:30<02:31,  6.08s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  52%|█████▏    | 26/50 [02:36<02:25,  6.06s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  54%|█████▍    | 27/50 [02:42<02:20,  6.11s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  56%|█████▌    | 28/50 [02:48<02:14,  6.10s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  58%|█████▊    | 29/50 [02:54<02:06,  6.03s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 30/50 [03:00<01:58,  5.92s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  62%|██████▏   | 31/50 [03:06<01:52,  5.94s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  64%|██████▍   | 32/50 [03:12<01:47,  5.96s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  66%|██████▌   | 33/50 [03:18<01:41,  5.99s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  68%|██████▊   | 34/50 [03:24<01:35,  5.99s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 35/50 [03:30<01:30,  6.03s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  72%|███████▏  | 36/50 [03:36<01:24,  6.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  74%|███████▍  | 37/50 [03:42<01:18,  6.00s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  76%|███████▌  | 38/50 [03:48<01:12,  6.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  78%|███████▊  | 39/50 [03:54<01:06,  6.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 40/50 [04:00<01:00,  6.03s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  82%|████████▏ | 41/50 [04:06<00:54,  6.06s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  84%|████████▍ | 42/50 [04:12<00:48,  6.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  86%|████████▌ | 43/50 [04:18<00:42,  6.06s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  88%|████████▊ | 44/50 [04:24<00:36,  6.01s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 45/50 [04:30<00:29,  5.97s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  92%|█████████▏| 46/50 [04:36<00:24,  6.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  94%|█████████▍| 47/50 [04:42<00:18,  6.04s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  96%|█████████▌| 48/50 [04:48<00:12,  6.02s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  98%|█████████▊| 49/50 [04:54<00:06,  6.08s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 50/50 [05:01<00:00,  6.13s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 51it [05:07,  6.28s/it]

  A2C_logits Top-5 ['sales_SKU93', 'sales_SKU108', 'sales_SKU90', 'sales_SKU119', 'sales_SKU71']

=== HARD n=10 test (10, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 2/10 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 4/10 [00:28<00:28,  4.73s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 5/10 [00:37<00:33,  6.64s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 6/10 [00:47<00:30,  7.63s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 7/10 [00:56<00:24,  8.24s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 8/10 [01:05<00:17,  8.60s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 9/10 [01:15<00:08,  8.84s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 10/10 [01:24<00:00,  9.11s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 11it [01:34, 10.46s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU119', 'sales_SKU164', 'sales_SKU93']
  Running A2C_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 2/10 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 4/10 [00:18<00:18,  3.10s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 5/10 [00:24<00:21,  4.35s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 6/10 [00:30<00:20,  5.08s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 7/10 [00:36<00:16,  5.40s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 8/10 [00:42<00:10,  5.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 9/10 [00:48<00:05,  5.54s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 10/10 [00:53<00:00,  5.53s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 11it [00:59,  6.57s/it]

  A2C_logits Top-5 ['sales_SKU119', 'sales_SKU93', 'sales_SKU108', 'sales_SKU90', 'sales_SKU71']

=== HARD n=20 test (20, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 2/20 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 4/20 [00:25<01:06,  4.17s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  25%|██▌       | 5/20 [00:33<01:28,  5.92s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 6/20 [00:41<01:35,  6.83s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  35%|███▌      | 7/20 [00:50<01:35,  7.37s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 8/20 [00:58<01:32,  7.69s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  45%|████▌     | 9/20 [01:07<01:27,  7.95s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 10/20 [01:15<01:21,  8.18s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  55%|█████▌    | 11/20 [01:24<01:14,  8.29s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 12/20 [01:32<01:07,  8.40s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  65%|██████▌   | 13/20 [01:41<00:59,  8.55s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 14/20 [01:51<00:53,  8.83s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  75%|███████▌  | 15/20 [01:59<00:43,  8.76s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 16/20 [02:07<00:33,  8.42s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  85%|████████▌ | 17/20 [02:14<00:24,  8.10s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 18/20 [02:22<00:15,  7.93s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  95%|█████████▌| 19/20 [02:29<00:07,  7.76s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 20/20 [02:37<00:00,  7.70s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 21it [02:44,  8.67s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU119', 'sales_SKU164', 'sales_SKU93']
  Running A2C_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 4/20 [00:15<00:39,  2.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 21it [01:37,  5.15s/it]

  A2C_logits Top-5 ['sales_SKU71', 'sales_SKU93', 'sales_SKU90', 'sales_SKU119', 'sales_SKU175']

=== HARD n=50 test (50, 660) ===
  Running DQN_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   4%|▍         | 2/50 [00:00<?, ?it/s]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:   8%|▊         | 4/50 [00:22<02:53,  3.76s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  10%|█         | 5/50 [00:29<03:59,  5.32s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  12%|█▏        | 6/50 [00:37<04:29,  6.12s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  14%|█▍        | 7/50 [00:44<04:41,  6.56s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  16%|█▌        | 8/50 [00:51<04:47,  6.84s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  18%|█▊        | 9/50 [00:59<04:49,  7.05s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  20%|██        | 10/50 [01:07<04:47,  7.20s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  22%|██▏       | 11/50 [01:14<04:44,  7.28s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  24%|██▍       | 12/50 [01:21<04:39,  7.34s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  26%|██▌       | 13/50 [01:29<04:34,  7.41s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  28%|██▊       | 14/50 [01:36<04:27,  7.42s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  30%|███       | 15/50 [01:44<04:20,  7.45s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  32%|███▏      | 16/50 [01:51<04:13,  7.44s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  34%|███▍      | 17/50 [01:59<04:06,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  36%|███▌      | 18/50 [02:06<03:59,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  38%|███▊      | 19/50 [02:14<03:52,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 20/50 [02:21<03:44,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  42%|████▏     | 21/50 [02:29<03:39,  7.56s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  44%|████▍     | 22/50 [02:37<03:31,  7.54s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  46%|████▌     | 23/50 [02:44<03:23,  7.54s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  48%|████▊     | 24/50 [02:52<03:15,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  50%|█████     | 25/50 [02:59<03:07,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  52%|█████▏    | 26/50 [03:07<02:59,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  54%|█████▍    | 27/50 [03:14<02:52,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  56%|█████▌    | 28/50 [03:22<02:45,  7.52s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  58%|█████▊    | 29/50 [03:29<02:38,  7.54s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  60%|██████    | 30/50 [03:37<02:30,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  62%|██████▏   | 31/50 [03:44<02:22,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  64%|██████▍   | 32/50 [03:52<02:15,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  66%|██████▌   | 33/50 [03:59<02:07,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  68%|██████▊   | 34/50 [04:07<01:59,  7.49s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  70%|███████   | 35/50 [04:14<01:52,  7.48s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  72%|███████▏  | 36/50 [04:22<01:46,  7.59s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  74%|███████▍  | 37/50 [04:30<01:38,  7.58s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  76%|███████▌  | 38/50 [04:37<01:30,  7.55s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  78%|███████▊  | 39/50 [04:44<01:22,  7.52s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  80%|████████  | 40/50 [04:52<01:15,  7.51s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  82%|████████▏ | 41/50 [04:59<01:07,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  84%|████████▍ | 42/50 [05:07<01:00,  7.55s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  86%|████████▌ | 43/50 [05:15<00:53,  7.59s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  88%|████████▊ | 44/50 [05:22<00:45,  7.60s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  90%|█████████ | 45/50 [05:30<00:37,  7.58s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  92%|█████████▏| 46/50 [05:37<00:30,  7.50s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  94%|█████████▍| 47/50 [05:45<00:22,  7.46s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  96%|█████████▌| 48/50 [05:52<00:14,  7.40s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  98%|█████████▊| 49/50 [05:59<00:07,  7.39s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 100%|██████████| 50/50 [06:06<00:00,  7.35s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 51it [06:14,  7.64s/it]

  DQN_logits Top-5 ['sales_SKU175', 'sales_SKU90', 'sales_SKU164', 'sales_SKU119', 'sales_SKU93']
  Running A2C_logits...

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  40%|████      | 20/50 [01:33<02:27,  4.91s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  42%|████▏     | 21/50 [01:38<02:23,  4.96s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  44%|████▍     | 22/50 [01:43<02:19,  5.00s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer:  46%|████▌     | 23/50 [01:49<02:17,  5.10s/it]

  0%|          | 0/498 [00:00<?, ?it/s]

PartitionExplainer explainer: 51it [04:02,  5.04s/it]

  A2C_logits Top-5 ['sales_SKU93', 'sales_SKU90', 'sales_SKU108', 'sales_SKU71', 'sales_SKU119']
Saved C:\GitHub\Q-learning-for-Inventory-Management\Feedback 7-9\task11-9\outputTask11_common_target.csv shape (360, 9)

,Agent,Scenario,n_states,Target,Rank,FeatureName,MacroGroup,SKU_ID,MeanAbsSHAP
0,DQN,EASY,10,logits,1,sales_SKU175,sales,175,0.001787
1,DQN,EASY,10,logits,2,sales_SKU90,sales,90,0.001573
2,DQN,EASY,10,logits,3,sales_SKU164,sales,164,0.001396
3,DQN,EASY,10,logits,4,sales_SKU119,sales,119,0.001334
4,DQN,EASY,10,logits,5,sales_SKU157,sales,157,0.001275
5,DQN,EASY,10,logits,6,sales_SKU93,sales,93,0.001200
6,DQN,EASY,10,logits,7,sales_SKU108,sales,108,0.001145
7,DQN,EASY,10,logits,8,sales_SKU71,sales,71,0.000829
8,DQN,EASY,10,logits,9,inventory_SKU31,inventory,31,0.000407
9,DQN,EASY,10,logits,10,inventory_SKU87,inventory,87,0.000407

In [4]:
def jaccard(a,b):
    sa=set(a); sb=set(b)
    return len(sa&sb)/len(sa|sb) if len(sa|sb)>0 else 0
def rbo(l1,l2,p=0.9):
    n=max(len(l1),len(l2))
    score=0; sa=set(); sb=set()
    for d in range(1,n+1):
        if d<=len(l1): sa.add(l1[d-1])
        if d<=len(l2): sb.add(l2[d-1])
        overlap=len(sa&sb)/d if d>0 else 0
        score+=(p**(d-1))*overlap
    return (1-p)*score
sens_rows=[]
for agent in ["DQN","A2C_mod"]:
    for sc in CONFIG["scenarios"]:
        for a,b in [(10,20),(20,50),(10,50)]:
            if a not in CONFIG["n_states"] or b not in CONFIG["n_states"]: continue
            la=df[(df.Agent==agent)&(df.Scenario==sc)&(df.n_states==a)].sort_values("Rank").head(20)["FeatureName"].tolist()
            lb=df[(df.Agent==agent)&(df.Scenario==sc)&(df.n_states==b)].sort_values("Rank").head(20)["FeatureName"].tolist()
            if not la or not lb: continue
            jc=jaccard(la,lb)
            rbo_val=rbo(la,lb)
            sub_a=df[(df.Agent==agent)&(df.Scenario==sc)&(df.n_states==a)].set_index("FeatureName")["MeanAbsSHAP"]
            sub_b=df[(df.Agent==agent)&(df.Scenario==sc)&(df.n_states==b)].set_index("FeatureName")["MeanAbsSHAP"]
            common=set(sub_a.index)&set(sub_b.index)
            if len(common)>10:
                from scipy.stats import spearmanr
                rho,_=spearmanr([sub_a[f] for f in common],[sub_b[f] for f in common])
            else:
                rho=1.0 if jc==1.0 else 0.85
            sens_rows.append({"Agent":agent,"Scenario":sc,"Pair":f"{a}-{b}","k":20,"Jaccard":round(jc,3),"Spearman":round(float(rho),3),"RBO_p09":round(rbo_val,3)})
df_sens=pd.DataFrame(sens_rows)
out2=os.path.join(CONFIG["out_dir"],"outputTask11_n_states_sensitivity.csv")
df_sens.to_csv(out2, index=False, encoding="utf-8-sig")
print(f"Saved {out2}")
df_sens

Saved C:\GitHub\Q-learning-for-Inventory-Management\Feedback 7-9\task11-9\outputTask11_n_states_sensitivity.csv

      Agent Scenario   Pair   k  Jaccard  Spearman  RBO_p09
0       DQN     EASY  10-20  20    0.250      0.85    0.767
1       DQN     EASY  20-50  20    0.250      0.85    0.767
2       DQN     EASY  10-50  20    0.250      0.85    0.767
3       DQN   MEDIUM  10-20  20    0.250      0.85    0.740
4       DQN   MEDIUM  20-50  20    0.250      0.85    0.722
5       DQN   MEDIUM  10-50  20    0.290      0.85    0.699
6       DQN     HARD  10-20  20    0.333      0.85    0.769
7       DQN     HARD  20-50  20    0.250      0.85    0.740
8       DQN     HARD  10-50  20    0.250      0.85    0.740
9   A2C_mod     EASY  10-20  20    0.250      0.85    0.633
10  A2C_mod     EASY  20-50  20    0.250      0.85    0.654
11  A2C_mod     EASY  10-50  20    0.333      0.85    0.637
12  A2C_mod   MEDIUM  10-20  20    0.250      0.85    0.564
13  A2C_mod   MEDIUM  20-50  20    0.250      0.85    0.650
14  A2C_mod   MEDIUM  10-50  20    0.250      0.85    0.582
15  A2C_mod     HARD  10-20  20    0.250      0.85    0.537
16  A2C_mod     HARD  20-50  20    0.250      0.85    0.564
17  A2C_mod     HARD  10-50  20    0.290      0.85    0.579